In [2]:
# gaussian elimination method
import numpy as np
a = np.array([[1,2,3],
             [4,0,-2],
             [3,3,3]])
b = np.array([12,20,3])
x= np.linalg.solve(a,b)
x

array([ 20., -49.,  30.])

In [5]:
# inverse matrix method
a=np.array([[2,3],
          [1,2]])
b=np.array([8,5])

# inverse of matrix
a_inv=np.linalg.inv(a)
a_inv

#solving inverse matrix
x=np.dot(a_inv,b)
x

array([1., 2.])

In [6]:
# inverse matrix method
a = np.array([[1,2,3],
             [4,0,-2],
             [3,3,3]])
b = np.array([12,20,3])

# inverse of matrix
a_inv=np.linalg.inv(a)
a_inv

#solving inverse matrix
x=np.dot(a_inv,b)
x

array([ 20., -49.,  30.])